### ISSUE TITLE
Add `ineg` encoding for scalar integers

### ISSUE THREAD

**Issue by abrown** [CraneStation/cranelift#1053] opened 2019-09-20 18:00 UTC
On x86, the new `ineg` instruction added for SIMD support (see #1050) can also be encoded for scalar integers using the `NEG` instruction. To do so, however, may require some refactoring of `PerCpuModeEncodings` to more easily pass the bits needed for the reg field of the ModR/M byte (see comment on https://github.com/CraneStation/cranelift/pull/1050#discussion_r326724852). Once there is a cleaner way to add those bits, the `ineg` instruction can be encoded for x86.

**Comment by bnjbvr** [comment] 2019-09-23 12:53
Thanks for opening an issue! It's a duplicate of #793, so I'll close this one and port your comment about PerCpuModeEncodings there.

**Closed by bnjbvr** 2019-09-23 12:53 UTC
