### ISSUE TITLE
Compiles under this command but it shouldn't

### ISSUE THREAD

**Issue by carolinecullen** [CraneStation/cranelift#374] opened 2018-06-25 21:11 UTC
cton-util compile --target=x86_64 filetests/verifier/memory.cton

This command should get a verifier error, yet it succeeds.

**Comment by sunfishcode** [comment] 2018-07-06 23:11
This looks like it might be the same issue as #385. cton-util does exit with an error exit code:
```
$ target/debug/cton-util compile --target=x86_64 filetests/verifier/memory.cton 
function %deref_cycle() fast {
    gv0 = globalsym %
    gv1 = deref(gv2)-32
    gv2 = deref(gv1)

ebb1:

}
$ echo $?
1
```
so it looks like the problem is that the error message isn't getting printed.

**Comment by sunfishcode** [comment] 2018-09-07 00:03
This is now fixed in @6A's recent work!
```
$ clif-util compile --target=x86_64 filetests/verifier/memory.clif 
function %cycle() fast {
    gv0 = load.i32 notrap aligned gv1
    ^~~~ verifier gv0: global value cycle: [gv0, gv1]

    gv1 = load.i32 notrap aligned gv0-32

ebb1:
    return
}
```

**Closed by sunfishcode** 2018-09-07 00:03 UTC
